### ISSUE TITLE
Consider expanding AWS "Prepare the AWS infrastructure provider" page

### ISSUE THREAD

**Issue by s3rj1k** [k0rdent/olddocs#15]
Consider expanding AWS "Prepare the AWS infrastructure provider" page with links on how to setup software prerequisites.

**Comment by DinaBelova** [comment]
@s3rj1k can you please elaborate on this? I was under assumption we discussed it somewhere that https://mirantis.github.io/project-2a-docs/quick-start/aws/ is covering this topic, but was not able to find this conversation. Is it still accurate issue?

**Comment by s3rj1k** [comment]
Issue was created before major Docs refactor and was referencing absence of CLI utilities section in DevDocs https://github.com/Mirantis/hmc/blob/main/docs/dev.md#install-required-clis.

Now there are other issues, like broken links in DevDocs, like this one https://github.com/Mirantis/hmc/blob/main/docs/aws/main.md#prepare-the-aws-infra-provider

**Comment by DinaBelova** [comment]
can you please adjust issue description to the most latest desired content?

**Comment by s3rj1k** [comment]
I think we can close this issue, as https://github.com/Mirantis/hmc/blob/main/docs/dev.md#install-required-clis solves the tooling question and https://github.com/Mirantis/hmc/blob/main/docs/aws/main.md#prepare-the-aws-infra-provider does not exist in Docs, presumably replaced by https://mirantis.github.io/project-2a-docs/quick-start/aws/.

Closing.
