### ISSUE TITLE
Sync dev-docs from original HMC repo.

### ISSUE THREAD

**Issue by s3rj1k** [k0rdent/olddocs#19]
Sync dev-docs from original HMC repo.

(https://github.com/Mirantis/hmc/blob/main/docs/dev.md)

**Comment by a13x5** [comment]
It was already discussed here Mirantis/hmc#404
These docs are highly coupled with Makefile and other dev specific stuff, so it's better for them to reside in hmc repo.

**Comment by s3rj1k** [comment]
IMO this is very bad that we have same docs in two places and they are out of sync.

We should have them in one place and if needed link one on another.

**Comment by a13x5** [comment]
Ah ok got it, I will delete them from here then. Probably they were added by mistake here
